### PR TITLE
Update headers-ja.properties

### PR DESCRIPTION
**Pull request by kiki-ja**
Word fix.
1007: ,日付 --> 日時
1028: 添付ファイルあり --> 添付ファイル

### CODE REVIEW

**Comment by kiki-ja** [comment]
@cleidigh

Fix it as shown in the screenshot below.

PrintingTools NG 205b3 ja-Option-Headers

**Comment by kiki-ja** [comment]
@cleidigh

I would like to see localization available for all languages.

**Comment by cleidigh** [comment]
everything will be localized

just not there yet

**Comment by kiki-ja** [comment]
@cleidigh

I was relieved.
When the localized file is completed, I will send it all translated into Japanese.

Thanks.

**Comment by cleidigh** [comment]
obsolete

**Pull request closed without merging**
